### PR TITLE
Configure LXC containers to use apt-cacher-ng by default

### PR DESCRIPTION
**Pull request by Dude4Linux**
I'm issuing this PR now because I want to get this in the queue for v15.0.  Sorry @JedMeister more work for you.

**Closes Issue [#1083](https://github.com/turnkeylinux/tracker/issues/1083)**
- configures containers to use `apt-cacher-ng` by default

**Partial fix for Issue [#244](https://github.com/turnkeylinux/tracker/issues/244)**  (if `10proxy` were added to `firstboot.d` in common)
- allows APT_PROXY to be preseeded (currently only in containers)

**IP Tables**
- eliminated unnecessary rules, e.g. ACCEPT rules in chains with default ACCEPT policy
- changed rule order to ensure rules are not bypassed
- commented all rules so we know what they are supposed to do
- added additional rules to protect `natbr0` containers
- added `ebtable` rule to protect `apt-cacher-ng port 3142` from external access

**apt-cacher-ng**
- changed binding so all containers can access the `apt-cacher-ng` service
- protected `apt-cacher-ng` from external access
- configured `apt-cacher-ng` to forward `https` (ssl) requests to upstream servers
- allow overriding default apt-proxy by preseeding `inithooks.conf` or setting in root environment var
- automatically configure `apt-cacher-ng` to forward to external apt-proxy, when specified above
- periodically check external proxy (5 minutes) and bypass if failed
- allow access to `apt-cacher-ng` maintenance page via `nginx ssl proxy` on port 12323

**TODO:**
- add link to `apt-cacher-ng` maintenance page through TurnKey web console pages
- document the use of the `apt-cacher-ng` maintenance page
- consider adding admin/password to protect `apt-cacher-ng` maintenance page

@JedMeister - I'd like to confirm it's okay to use port 12323 for `ssl` protected access to `apt-cacher-ng` maintenance page.
@qrntz @OnGle @alonswartz @lirazsiri - Because of the changes to `iptables-lxc` I'd like to have some other experts review my work.  I'm sure there must be something I overlooked.

### CODE REVIEW

**Comment by Dude4Linux** [comment]
@JedMeister - I got side tracked with needing to update my PDE to accommodate changes in LXC/LXD 3.0.1, so I haven't addressed the TODO list.  I was kinda waiting to hear from you about the use of port 12323 for the apt-cacher-ng maintenance pages.  At this point we could do one of several options:

1. Remove the nginx ssl proxy on port 12323, leaving the maintenance pages inaccessible as they were in v14.x.
2. Keep the nginx ssl proxy on port 12323, allowing info only access to the maintenance pages. In this case we should add a link (or tab) to the TurnKey web console page, and document the use of the apt-cacher-ng maintenance page(s).
3. Add a `firstboot.d` option to set an administrative user/password for the apt-cacher-ng maintenance pages.  This enables additional capability for managing apt-cacher-ng through the web interface.  I seem to recall that there was a naming convention for the inithooks/bin/setpassword.py.

**Comment by JedMeister** [comment]
@Dude4Linux 

> I'd like to confirm it's okay to use port 12323 for ssl protected access to apt-cacher-ng maintenance page

Apologies that I totally overlooked that! To be completely honest with you, I haven't done anything other than have a cursory glance over it at this point. I'm juggling way to many balls at the moment and am currently blocking on a few things that I really need to get done. Although, I guess, I'm blocking you too now! 

I have no fundamental issue with using that port, or any other port that we're not using. I've just had another quick look over the code to try to get myself back up to speed.

Whilst option 3 is sort of appealing, I'd probably be inclined to add it as a confconsole plugin, rather than an inithook. Then it's an added extra for those who want it; rather than a requirement. If we went that way, then I'd suggest going with option one, but then enable option three if it's run (i.e. password set).

Having said that, I reckon that the MVP is to have it working and stick with option one. We could always look at other options later.

**Comment by JedMeister** [comment]
@Dude4Linux - apologies on the delays on merging and releasing this one. Have just merged now and will do some testing and build it ASAP.

**Comment by JedMeister** [comment]
@Dude4Linux - thanks for your kind words and understanding... :smile: 

I haven't yet had a chance to properly test this and I'm under a bit of pressure to update a couple of previously released appliances ASAP (that have issues I missed during QA). So I may not be able to include LXC in the next batch. But v15.0 is nearly there and I will make it something of a priority.

If you do get a chance to have further look, please feel free to open a new PR. Please add a new (v15.1) changelog entry when you do. That way if the current build is already in progress it won't matter and we'll do a v15.1 release sometime soon. If v15.0 build isn't already past the point of no return, then I can squeeze it into the v15.0 version and just merge the 2 changelog entries (into a single v15.0 entry).

Thanks for the confirmation re apt-cacher-ng and potential security issues. If I get a chance, I'll have a quick look at the docs and tweak as/if need be.

**Pull request merged**
