### PR TITLE
15.0 update

### PR DESCRIPTION
**Pull request by OnGle**
- Fix networking caused by grub config in overlay
- Removes python-lxc (could not find anything that was using it and no documented reason for it being installed)

### CODE REVIEW

**Comment by JedMeister** [comment]
@OnGle

Looks awesome mate! Closes https://github.com/turnkeylinux/tracker/issues/878! :smile: 

Please let me know when it's good to merge.

----

@Dude4Linux

Do you have any input at all on these changes? Seems to cover the issue of version to download quite nicely IMO...

FWIW, we'll be leaving release of the v15.0 LXC appliance until we have some v15.0 containers on the mirror ready to test. So there is no rush on this. 

We can always open another PR in the future if you would like to see some tweaks.

**Comment by Dude4Linux** [comment]
@JedMeister I've also been working on a 15.0 update for LXC at https://github.com/Dude4Linux/lxc/tree/updates-for-15.0-release
I can see that there is some overlap with Stefan's work, but nothing that can't be resolved.
I haven't issued a pull request yet because I have been learning a lot about containers while writing 'lxd-make-image' for TKLdev.  The script uses the build/root.patched produced by product.mk, creates a new build/rootfs, applies all the changes needed for containers including metadata and templates for v.2 containers, then creates a tarbar that can be imported as a v.2 image.  I'll be uploading this to TurnKey PDE as soon as I've completed the documentation.
There are several things I learned about containers, that I want to incorporate in the 15.0 lxc-turnkey template before I issue the pull request.
Although lxd-make-image could be included as is in TKLdev 15.0, I'd like to look into integrating it into product.mk as an additional make target.  That way you could skip the production of product.iso if all you want is the product container image, e.g. 'make lxd'  instead of 'make' followed by 'lxd-make-image'.
One issue we need to discuss is a naming convention for LXC v.2 images and how to distribute them via the mirror system.

**Comment by JedMeister** [comment]
@Dude4Linux:

> I've also been working on a 15.0 update for LXC at https://github.com/Dude4Linux/lxc/tree/updates-for-15.0-release I can see that there is some overlap with Stefan's work, but nothing that can't be resolved.

Ok great. I'll merge this one now then. You can open another when you're ready. As I say, it'll be a little while before we'll be building the LXC appliance for v15.0 anyway.

> I haven't issued a pull request yet because I have been learning a lot about containers while writing 'lxd-make-image' for TKLdev. The script uses the build/root.patched produced by product.mk, creates a new build/rootfs, applies all the changes needed for containers including metadata and templates for v.2 containers, then creates a tarbar that can be imported as a v.2 image. I'll be uploading this to TurnKey PDE as soon as I've completed the documentation. There are several things I learned about containers, that I want to incorporate in the 15.0 lxc-turnkey template before I issue the pull request. Although lxd-make-image could be included as is in TKLdev 15.0, I'd like to look into integrating it into product.mk as an additional make target. That way you could skip the production of product.iso if all you want is the product container image, e.g. 'make lxd' instead of 'make' followed by 'lxd-make-image'.

Ok cool. That sounds like it will be a bonus for developers that use LXC. I'm sure that I personally could make use of it too as I often use LXC for testing.

Although I still think that for building "official" appliances, using buildtasks to process ISOs is the best way for us to do it internally. It maintains consistency of the appliance code and packages etc, across buildtypes, whilst still allowing us to make build specific changes. That's probably most important for AWS builds, but has relevance elsewhere too.

An easier way for end users to use TKLDev to build direct to whatever build they prefer would certainly be a plus. Although, I do have some concerns about repeating ourselves in multiple places. I mean, if we go that path, then that will make buildtasks somewhat redundant for end users. I have concerns that we may end up with divergent but somewhat duplicated processes. I.e. a result where appliances built with buildtasks are (potentially) different to appliances built within the app code root (via `make`).

Perhaps what we'd be better off doing, is building on buildtasks to allow that to build direct to any buildtype (rather than just building or processing an iso)? Perhaps allowing the scripts to take switches that would support the different build scenarios? Then the same modifications/additions/etc could be used, regardless of the process being used and the end result would be consistent.

I've also been wanting to make the buildtasks scripts accessible (and executable) anywhere, rather than just within the buildtasks directory. Perhaps it would make sense to do that as part of this work (so that users don't need to `cd buildtasks` before they build to specific buildtypes?

Anyway, good stuff to explore and consider. 

My last concern though is making fairly radical changes such as this, so close to our already long overdue v15.0 release. Adding additional build infrastructure complexity this close to the v15.0 release sounds like a bad idea to me. So my preference would be to get v15.0 out the door (ASAP) then we could start looking at this for v15.1. 

The other thing to keep in mind is that, whilst not directly relevant to these discussions, as of v14.2, we now don't need to keep all the appliances at the same version. That will allow us to do much more rapid releases of individual appliances. And even if we don't get LXC2 builds in the initial v15.0 release, there's no reason why we couldn't add them a little later.

> One issue we need to discuss is a naming convention for LXC v.2 images and how to distribute them via the mirror system.

So would these images be compatible with Proxmox? Assuming not, then my inclination would be to stick to the current TurnKey naming convention. FWIW the only reason LXC container templates are different is we need to comply with Proxmox naming convention to allow flawless integration with that. 

The current TurnKey convention is `turnkey-APP_NAME-TKL_VERSION-DEB_CODENAME-BUILDTYPE.EXT`. Sometimes the `BUILDTYPE` can be omitted if the `EXT` makes it redundant, e.g. `turnkey-core-14.2-jessie-amd64.iso` or `turnkey-core-14.2-jessie-amd64.ova`. In other cases, it makes sense to keep it explicit, e.g. `turnkey-core-14.2-jessie-amd64-openstack.qcow2`, `turnkey-core-14.2-jessie-amd64-vmdk.zip` or `turnkey-core-14.2-jessie-amd64-xen.tar.bz2`.

So I would suggest something like `turnkey-APP_NAME-TKL_VERSION-jessie-amd64-lxc2.xz`, so for v15.0 core, it's be `turnkey-core-15.0-jessie-amd64-lxc2.xz`.

**Comment by Dude4Linux** [comment]
@JedMeister 
> So would these images be compatible with Proxmox? Assuming not, then my inclination would be to stick to the current TurnKey naming convention. FWIW the only reason LXC container templates are different is we need to comply with Proxmox naming convention to allow flawless integration with that.

In theory, the .lxc2 images should be compatible with both Proxmox and the LXC v.1 appliance.  I'm not at home now, so I have no way to check on what would be required to use an image with Proxmox but it shouldn't be too difficult to do.
I've accepted your suggestion on naming conventions i.e. turnkey-core-14.2-jessie-amd64-lxc2.tar.xz or turnkey-core-15.0-stretch-amd64-lxc2.tar.xz  We could also use -lxd- instead of -lxc2-.

**Comment by JedMeister** [comment]
Hey @Dude4Linux - apologies on my delayed response to this thread. It's been a fairly frustrating few weeks lately. I'm trying to get v15.0 (at least an RC of Core) out the door ASAP but I keep hitting roadblocks... Then the Easter break (and Passover for the Israeli guys) has also slowed things down a little. Anyway...

> In theory, the .lxc2 images should be compatible with both Proxmox and the LXC v.1 appliance. I'm not at home now, so I have no way to check on what would be required to use an image with Proxmox but it shouldn't be too difficult to do.

Ok, well that sounds really promising! Having a single build that would support all of them would be awesome!

> I've accepted your suggestion on naming conventions i.e. turnkey-core-14.2-jessie-amd64-lxc2.tar.xz or turnkey-core-15.0-stretch-amd64-lxc2.tar.xz We could also use -lxd- instead of -lxc2-.

Ok cool. Although, if it will be completely compatible with LXD/LXC2, LXC(1) and Proxmox, then my preference would be to stick with the current LXC/Proxmox build naming (as then it will "just work" on Proxmox, without us having to host 2 separate builds). But no need to worry about that too much for now IMO. Probably best to cross that bridge when we get to it... My 2c anyway.

PS Hope you had a good Easter! :smile:

**Pull request merged**
