### PR TITLE
Update for 14.0 release

### PR DESCRIPTION
**Pull request by Dude4Linux**
The v14.0 release is now ready for code review and testing.  ~~The only remaining task is to build and include the python2-lxc package.~~  I've decided against adding the '-u|--uri' option at this time.  Perhaps it can be included in v14.1.

### CODE REVIEW

**Comment by ZitZ** [comment]
Dude,

I was testing your modifications to the lxc-turnkey template, on a plain debian (non-turnkey) system, as i was working on similar modifications.

I noticed that the resulting container, when started with lxc-start -dn NAME takes over the 4 ttys. This doesn't seem like a good behavior if the intent is to create a system that hosts many headless containers. I got around it by commenting out the mknod line. In my opinion, you can administer the containers best by using lxc-attach --clear-env -n.

It also seems to not set the root password to what I have set in inithooks, it leaves it blank. Which to me isn't a big deal, and I don't believe it is an issue with the template.

I'm still looking into all of this.

Are you seeing any similar issues?

**Comment by Dude4Linux** [comment]
@ZitZ Have you pulled a recent version of my code?  There was a problem loading inithooks in the early versions which was fixed in commit 5c0615f. Basically the template was copying the inithooks.conf file, but didn't make sure it was executable.  It took me way too long to figure out what was wrong.
As for the number of ttys used, the v13.0 template used 3 ttys.  My template was based on the debian template which initializes 4 ttys as most other templates do.  I'm not aware that this would cause problems with many containers on the same host.  I've had as many as eight running on my host system without noting any problems.  If you have additional information on the subject I'd be happy to consider it.
At this time, I aware of one remaining problem with the latest version.  The nginx-proxy program does not handle the container cert/key for a container using lvm as a backing store.  I'm currently researching the best way to solve the problem.
Thanks for taking the time to help with the testing.

**Comment by ZitZ** [comment]
@Dude4Linux 

I'm not concerned with the number of ttys.

what i'm seeing is when i start the container in daemon mode, the container takes control of all 4 host ttys. Then when you start your next container the same way, that container will take over the host ttys.

Should this be happening?

**Comment by Dude4Linux** [comment]
@ZitZ You are absolutely right about setting lxc.autodev = 1.  I based the lxc-turnkey template on the current 'jessie' version of the lxc-debian template.  I'm aware of some issues with the debian template and thought I had fixed them all.  According to the history on github, https://github.com/lxc/lxc/commit/124fa0a869c4cf5b4dc3ea2281446df32f0a7980#diff-e98d6f004e6cc03e79d6a030e93eba0f, lxc.autodev = 1 is now the default.  Also lxc.kmsg =0 has been made a default.  I can't make the changes the same way as upstream, but I think I see a way that will work for all templates and won't break when a newer version of lxc is installed from backports.  I'll test the changes and push a new commit.

Thanks again for catching this.

**Comment by ZitZ** [comment]
@Dude4Linux  Hey. No Problem. Sorry for sending messages before I had fully analyzed the problem.

I'm not sure I follow why we wouldn't want lxc.autodev = 1 regardless?

**Comment by Dude4Linux** [comment]
@ZitZ Hey Paul, if you have the time, please give my latest push a spin.  I made lxc.autodev = 1 by default.  I also did a major update to nginx-proxy to handle new v14.0 cert/key locations and backing stores other than 'dir'.

**Comment by ZitZ** [comment]
@Dude4Linux , Hi John, this is looking like it did the trick. Good work!

**Comment by Dude4Linux** [comment]
@ZitZ Thanks Paul.  Keep looking for things that need to be fixed.  I found one this afternoon.  The permissions on the copies of the container certs & keys created by nginx-proxy need to be changed for security.  I'm still working on a few more ideas.

**Comment by JedMeister** [comment]
Great work guys! :+1: 

@Dude4Linux Apologies that I haven't had a chance to do more... At this point my intended involvement will be pushed back another week (again) at the earliest... However, it sounds like me being busy elsewhere is actually a good thing - allowing the LXC app to just keep getting better! :smile: 

Thanks again John for your hard work on this. And thanks @ZitZ for your involvement too!

**Comment by Dude4Linux** [comment]
I've relaxed the restrictions on dnsmasq to allow dns queries from hosts on the local subnets.  This makes it easier to run an Ansible playbook to create, test, and destroy containers. I modified nginx-proxy so that it adds the domain component of a proxy to the dnsmasq hosts.conf. Ansible can then pull a webpage through the proxy, testing both it and the proxy.  Another handy option was the ability to list the available proxies in the form of {domain container} pairs.

An example playbook looks like this
```
---
- hosts: lxc

  vars:
    host_key_checking: false
    ssh_user: '{{lookup("env", "USER")}}'
    ssh_key: '{{lookup("file", "~/.ssh/id_rsa.pub")}}'
 
    appliances:
    - lxc
    - wordpress
    - drupal7
    - jenkins

  tasks:
  - name: Clear lxc lock
    # required by bug in ansible installaion
    file: path=/var/lock/subsys/lxc state=absent

  - name: Ensure known_hosts
    file: path=/root/.ssh/known_hosts state=touch mode=0644

  - name: Clear known_hosts
    # remove previous entries, if any, from known_hosts
    shell: "ssh-keygen -R turnkey-{{item}}-container"
    shell: "ssh-keygen -R $(host turnkey-{{item}}-container | cut -d ' ' -f 4)"
    with_items: "{{ appliances }}"

  - name: Create TurnKey containers
    # Create container
    lxc_container:
      name: "turnkey-{{item}}-container"
      container_log: true
      config: /etc/lxc/natbridge.conf
      backing_store: lvm
      vg_name: turnkey
      state: started
      template: turnkey
      template_options: "{{item}} --version=13.0-wheezy"
      container_command: |
        # make sure required packages are present
        apt-get -yq install python python-apt
        # install the ansible user's public key
        mkdir -p /root/.ssh
        echo '{{ssh_key}}' >> /root/.ssh/authorized_keys

    register: "{{item}}_container_info"
    with_items: "{{ appliances }}"

  - name: Debug container info
    debug: var="{{item}}_container_info"
    with_items: "{{ appliances }}"

  - name: Check web proxy
    command: "nginx-proxy -c -d {{item}}.local.lxc -n turnkey-{{item}}-container"
    register: command_result
    changed_when: "command_result.rc == 1"
    failed_when: "command_result.rc == 2"
    with_items: "{{ appliances }}"

  - name: Create web proxy
    command: "nginx-proxy -d {{item}}.local.lxc -n turnkey-{{item}}-container"
    register: command_result
    changed_when: "command_result.rc == 1"
    failed_when: "command_result.rc == 2"
    with_items: "{{ appliances }}"

  - name: Wait for appliance
    wait_for:
      host: "turnkey-{{item}}-container"
      port: 80
      delay: 10
      state: started
    with_items: "{{ appliances }}"

  - name: Test appliance webpage
    uri:
      url: "http://{{item}}.local.lxc"
      return_content: yes
    register: webpage
    with_items: "{{ appliances }}"
 
  - name: Remove web proxy
    command: "nginx-proxy -r -d {{item}}.local.lxc -n turnkey-{{item}}-container"
    register: command_result
    changed_when: "command_result.rc == 1"
    failed_when: "command_result.rc == 2"
    with_items: "{{ appliances }}"

  - name: Shutdown TurnKey containers
    lxc_container:
      name: "turnkey-{{item}}-container"
      state: stopped
    with_items: "{{ appliances }}"

  - name: Destroy TurnKey containers
    lxc_container:
      name: "turnkey-{{item}}-container"
      state: absent
    with_items: "{{ appliances }}"
```

**Comment by Dude4Linux** [comment]
@JedMeister @qrntz @ZitZ Hey guys, would you please give this latest commit a try and let me know if you find any problems.  This is the last of the new features I want to add before the 14.0 release.  Only bug fixes will be made from not on.

**Comment by JedMeister** [comment]
Awesome work thanks John :+1: I'll have a look ASAP.

**Comment by Dude4Linux** [comment]
@JedMeister @qrntz I made one final tweak to fix a problem I had introduced earlier.  I can't remember why I added the server port to the host header in /etc/nginx/include/proxy.  It may have been related to getting jenkins to accept the proxy config, however it backfired and caused a problem with any appliance who issued a redirect from http to https.

I can't claim that we've found and fixed every bug, but I'm comfortable with proceeding with the 14.0 release.

**Comment by JedMeister** [comment]
Great work guys. Looking good. How close do you think we are to a release? Do you think this week is a possibility?

**Comment by qrntz** [comment]
I have no objections.

**Comment by Dude4Linux** [comment]
The last two commits change the iptables rules to form a basic security firewall to protect the natbr0 containers.  The bridged containers are fully exposed to the external network as would be expected.

**Comment by Dude4Linux** [comment]
This last change was needed to keep Webmin from trying to redirect to port 10000 after login.

**Comment by JedMeister** [comment]
Great work guys. Hoping to release this week! Yay! :smile:

**Comment by JedMeister** [comment]
Great work for a mammoth effort @Dude4Linux :smile: 

Thanks tons for your testing and input too @qrntz & @ZitZ 

The release should be complete by mid week...

**Comment by ZitZ** [comment]
@Dude4Linux

Yes, a well deserved shout out for making these updates!

On Mon, Jan 18, 2016 at 6:20 AM, Jeremy Davis <notifications@github.com>
wrote:

> Great work for a mammoth effort @Dude4Linux
> <https://github.com/Dude4Linux> [image: :smile:]
>
> Thanks tons for your testing and input too @qrntz
> <https://github.com/qrntz> & @ZitZ <https://github.com/ZitZ>
>
> The release should be complete by mid week...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/turnkeylinux-apps/lxc/pull/5#issuecomment-172501823>.
>



-- 
Time To Get an EKG, G!

**Pull request merged**
